version: '3.8'

services:
  setup:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.setup
      args:
        - WORKFLOW_NAME=${WORKFLOW_NAME:-hunyuan-fp8}
    image: heuristai/comfyui-release:setup-${WORKFLOW_NAME:-hunyuan-fp8}
    environment:
      - WORKFLOW_NAME=${WORKFLOW_NAME:-hunyuan-fp8}
    volumes:
      - comfyui_data:/root/ComfyUI

  comfyui:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.comfyui
    image: heuristai/comfyui-release:comfyui-${WORKFLOW_NAME:-hunyuan-fp8}
    restart: unless-stopped
    container_name: comfyui-container-gpu${GPU_DEVICE_ID:-0}-${COMFYUI_PORT:-8188}
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_DEVICE_ID:-0}']
              capabilities: [gpu]
    volumes:
      - comfyui_data:/root/ComfyUI
      - /tmp:/tmp
    environment:
      - COMFYUI_PORT=${COMFYUI_PORT:-8188}
    network_mode: "host"

  miner:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.miner
    image: heuristai/comfyui-release:miner-${WORKFLOW_NAME:-hunyuan-fp8}
    restart: unless-stopped
    container_name: miner-gpu${GPU_DEVICE_ID:-0}-${COMFYUI_PORT:-8188}
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${GPU_DEVICE_ID:-0}']
              capabilities: [gpu]
    volumes:
      - comfyui_data:/root/ComfyUI
      - ./logs:/app/miner/logs
    environment:
      - COMFYUI_PORT=${COMFYUI_PORT:-8188}
      - ERC20_ADDRESS=${ERC20_ADDRESS}
    network_mode: "host"
    depends_on:
      - comfyui

volumes:
  comfyui_data: